# Generated by Django 4.1.1 on 2022-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(blank=True)),
                ('ModifiedDate', models.DateTimeField(blank=True)),
                ('sistema', models.CharField(blank=True, max_length=100)),
                ('inquilino', models.TextField(blank=True)),
                ('demanda', models.TextField(blank=True)),
            ],
        ),
    ]
