# Generated by Django 3.2.15 on 2022-09-09 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='CreateDate',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='ModifiedDate',
        ),
        migrations.AddField(
            model_name='plano',
            name='adequacao',
            field=models.CharField(choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3),
        ),
        migrations.AddField(
            model_name='plano',
            name='aditivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='ans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_cadastro_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_cadastro_clientes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_cliente',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_itens',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_executora_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_responsavel_capacitacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_cadastro_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_cadastro_clientes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_itens',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='area_solicitante_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='atendimento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='canais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='capacitacao',
            field=models.CharField(choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3),
        ),
        migrations.AddField(
            model_name='plano',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 18, 51, 23, 418585), editable=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='cronograma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='desc_produto',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 18, 51, 23, 418616)),
        ),
        migrations.AddField(
            model_name='plano',
            name='n1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='n2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='necessidades',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_base',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_cadastro_base',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_cadastro_clientes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_cliente',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_itens',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_executora_usuario',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_risco',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_base',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_cadastro_base',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_cliente',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_itens',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_usuario',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plano',
            name='publicacao_executora_base',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='publicacao_executora_cadastro_base',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='publicacao_solicitante_base',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='publicacao_solicitante_cadastro_base',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='requisitos_LDPA',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='solucoes_impactadas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='sub_demanda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plano',
            name='demanda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plano',
            name='inquilino',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
