# Generated by Django 3.2.15 on 2022-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0002_auto_20220909_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
