# Generated by Django 3.2.15 on 2022-09-12 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0003_auto_20220912_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 18, 7, 20, 671319, tzinfo=utc), editable=False),
        ),
    ]
