# Generated by Django 3.2.15 on 2022-09-12 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0004_alter_plano_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 18, 18, 1, 937677, tzinfo=utc), editable=False),
        ),
    ]
