# Generated by Django 3.2.15 on 2022-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0005_alter_plano_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='anexo_contexto',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
