# Generated by Django 3.2.15 on 2022-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0006_auto_20220912_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='anexo_contexto',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
