# Generated by Django 3.2.15 on 2022-09-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0007_alter_plano_anexo_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='cronograma_implantacao',
            field=models.FileField(blank=True, max_length=255, upload_to='files'),
        ),
        migrations.AddField(
            model_name='plano',
            name='telas_sistema',
            field=models.FileField(blank=True, max_length=255, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='anexo_contexto',
            field=models.FileField(blank=True, max_length=255, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='cronograma',
            field=models.FileField(blank=True, max_length=255, upload_to='files'),
        ),
    ]
