# Generated by Django 3.2.15 on 2022-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0008_auto_20220912_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Em Elaboracao'), ('3', 'Inativo')], default='Ativo', max_length=13),
        ),
        migrations.AddField(
            model_name='plano',
            name='versao',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
