# Generated by Django 4.1.1 on 2022-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0009_auto_20221025_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='capacitacao',
            new_name='capacitacao1',
        ),
        migrations.AddField(
            model_name='plano',
            name='capacitacao2',
            field=models.CharField(choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3),
        ),
    ]
