# Generated by Django 4.1.1 on 2022-11-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0013_rename_capacitacao_plano_capacitacao1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='capacitacao1',
            new_name='capacitacao',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='capacitacao2',
        ),
    ]
