# Generated by Django 4.1.1 on 2022-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0020_alter_plano_capacitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='capacitacao1',
            field=models.CharField(blank=True, choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Sim', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='capacitacao2',
            field=models.CharField(blank=True, choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Sim', max_length=3, null=True),
        ),
    ]
