# Generated by Django 4.1.1 on 2022-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0021_plano_capacitacao1_plano_capacitacao2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='capacitacao1',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='capacitacao2',
        ),
    ]
