# Generated by Django 4.1.1 on 2022-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0022_remove_plano_capacitacao1_remove_plano_capacitacao2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='capacitacao',
            field=models.CharField(blank=True, choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3, null=True),
        ),
    ]
