# Generated by Django 4.1.1 on 2022-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0029_alter_plano_capacitacao2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='capacitacao2',
        ),
        migrations.AlterField(
            model_name='plano',
            name='capacitacao',
            field=models.CharField(choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3),
        ),
    ]
