# Generated by Django 4.1.1 on 2022-11-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0030_remove_plano_capacitacao2_alter_plano_capacitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='capacitacao',
            field=models.TextField(blank=True, choices=[('Sim', 'sim'), ('Nao', 'nao')], default='Nao', max_length=3),
        ),
    ]
