# Generated by Django 4.1.1 on 2022-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0031_alter_plano_capacitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='adequacao',
            field=models.TextField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Nao')], default='Nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='plano',
            name='capacitacao',
            field=models.TextField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Nao')], default='Nao', max_length=3),
        ),
    ]
