# Generated by Django 4.1.1 on 2022-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0032_alter_plano_adequacao_alter_plano_capacitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plano',
            name='necessidades',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plano',
            name='requisitos_LDPA',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plano',
            name='solucoes_impactadas',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
