# Generated by Django 4.1.1 on 2022-12-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0033_plano_responsavel_alter_plano_necessidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Em Elaboracao'), ('3', 'Inativo'), ('4', 'Desativado')], default='Ativo', max_length=13),
        ),
    ]
