# Generated by Django 4.1.1 on 2022-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0034_alter_plano_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='obs_solicitante_cadastro_cliente',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='plano',
            name='adequacao',
            field=models.TextField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Nao')], default='Nao', max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='area_executora_cliente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='capacitacao',
            field=models.TextField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Nao')], default='Nao', max_length=20),
        ),
    ]
