# Generated by Django 4.1.1 on 2022-12-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0035_plano_obs_solicitante_cadastro_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='obs_solicitante_cadastro_cliente',
            new_name='obs_solicitante_cadastro_clientes',
        ),
    ]
