# Generated by Django 4.1.1 on 2022-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0036_rename_obs_solicitante_cadastro_cliente_plano_obs_solicitante_cadastro_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
