# Generated by Django 4.1.1 on 2022-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0037_alter_plano_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='anexo_contexto',
            field=models.FileField(blank=True, default='Nenhum arquivo anexado', max_length=255, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='cronograma',
            field=models.FileField(blank=True, default='Nenhum arquivo anexado', max_length=255, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='cronograma_implantacao',
            field=models.FileField(blank=True, default='Nenhum arquivo anexado', max_length=255, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='telas_sistema',
            field=models.FileField(blank=True, default='Nenhum arquivo anexado', max_length=255, upload_to='files'),
        ),
    ]
