# Generated by Django 4.1.1 on 2022-12-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0039_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
