# Generated by Django 4.1.1 on 2022-12-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0040_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usuario',
        ),
    ]
