# Generated by Django 4.1.1 on 2023-01-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0043_pageview_delete_user_alter_plano_sistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
