# Generated by Django 4.1.1 on 2023-01-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0047_alter_accesscount_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessCount',
            new_name='Acesso',
        ),
    ]
