# Generated by Django 4.1.1 on 2023-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0048_rename_accesscount_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='Estrategia_de_implan_solucao',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='Volumetrias',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='abrangencia',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='ano_contrato',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='cronograma_elaboracao_execucaoPDA',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='fluxo_de_atendimento',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='identificacao_area_solicitante',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='informacoes_complementares',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='objetivo_plano_atendimento',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plano',
            name='processo_de_atendimento_usu',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='requisitos_cadastramento_clienteEusuario',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='plano',
            name='riscos_identificados',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
