# Generated by Django 4.1.1 on 2023-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0049_plano_estrategia_de_implan_solucao_plano_volumetrias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='n1Area',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='plano',
            name='n2Area',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='plano',
            name='Volumetrias',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plano',
            name='abrangencia',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plano',
            name='fluxo_de_atendimento',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plano',
            name='objetivo_plano_atendimento',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
