# Generated by Django 4.1.1 on 2023-01-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0051_plano_impactos_plano_mitigacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='AreaCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='DatafimCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='DatainiCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='ResponsavelCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='atividadeCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='statusCronograma',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
