# Generated by Django 4.1.1 on 2023-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0052_plano_areacronograma_plano_datafimcronograma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='informacoes_complementares',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
