# Generated by Django 4.1.1 on 2023-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0053_alter_plano_informacoes_complementares'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='cadastramento_itens_catalogo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
