# Generated by Django 4.1.1 on 2023-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0054_plano_cadastramento_itens_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='identificacao_area_solicitante',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('1', 'Em Elaboracao'), ('2', 'Em Aprovação'), ('3', 'Suspenso'), ('4', 'Concluído')], default='Ativo', max_length=13),
        ),
    ]
